name: godot-ci

on:
  push:
    branches: [ main ]

env:
  GODOT_VERSION: 4.6.2

jobs:
  export-game:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Export Godot project
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz
          relative_project_path: ./

        env:
          GITHUB_TOKEN: ${{ secrets.godotSecret }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.godotSecret }}
          tag: latest
          name: Latest Build
          artifacts: ./build/*
